[package]
name = "aoc_solve"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = "0.11"
chrono = "0.4"
clap = { version = "4.3", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

